export { createVueGrabAPI, installVueGrab } from './core/api.js';
export type { VueGrabOptions } from './core/api.js';
export type { OverlayOptions, OverlayStyle } from './core/overlay.js';
export { createToggleWidget } from './core/widget.js';
export { identifyComponent, extractMetadata } from './core/identifier.js';
export { createOverlayController } from './core/overlay.js';
export { createVueGrabPlugin } from './plugin.js';
export { default } from './plugin.js';
export { createVueGrabVitePlugin } from './vite.js';
export type { VueGrabVitePluginOptions } from './vite.js';
