export { createVueGrabAPI, installVueGrab } from './core/api';
export type { VueGrabOptions } from './core/api';
export type { OverlayOptions, OverlayStyle } from './core/overlay';
export { createToggleWidget } from './core/widget';
export { identifyComponent, extractMetadata } from './core/identifier';
export { createOverlayController } from './core/overlay';
export { createVueGrabPlugin } from './plugin';
export { default } from './plugin';
export { createVueGrabVitePlugin } from './vite';
export type { VueGrabVitePluginOptions } from './vite';
